### ISSUE TITLE
Saving of pathauto pattern fails

### ISSUE THREAD

**Issue by dawehner** [md-systems/pathauto#22]
I have a pathauto configuration which looks like the following:

```
taxonomy_term:
  _default: '[term:vocabulary]/[term:name]'
  blog_tags:
    _default: 'blog/[term:name]'
```

On top of that there is a panel page pointing to blog/%

If you run migrations creating all kind of terms, you end up with a stuf migration.
Once you remove the override for blog_tags it works again.
