### ISSUE TITLE
Language specific patterns not being applied

### ISSUE THREAD

**Issue by idflood** [md-systems/pathauto#92]
For instance the pattern defined for "all French Basic page path" are never applied. To reproduce:
1. Enable multiple languages
2. Make the page content type translatable
3. Define different path patterns for this content type.

Then only the "default pattern" is applied and never the language specific one.

**Comment by idflood** [comment]
The issue may be in `PathautoManager->getPatternByEntity()`. This function tries to get the config from:

```
$variables[] = "{$entity_type_id}.bundles.{$bundle}.languages.{$language}";
```

But in fact the config I get looks like this (without the .languages and instead `{$bundle}_{$language}`):

```
patterns:
  node:
    default: '/content/[node:title]'
    bundles:
      article:
        default: ''
      page:
        default: ''
      page_fr:
        default: '/page-fr/[node:title]'
      page_de:
        default: '/page-de/[node:title]'
      page_en:
        default: '/page-en/[node:title]'
```

edit:
One other issue is that this function do this:

```
if ($pattern = trim($config->get('patterns.' . $variable)))
```

But in fact `$config->get('patterns.' . $variable)` doesn't return a string but an array with a ['default'] if there is a result.
